-- Migration 001: Create base tables (from existing kitch_* schema)
-- This migration assumes you already have kitch_customer, kitch_item_catalg, kitch_category, kitch_status, kitch_payment tables
-- If not, uncomment and modify these table definitions as needed

-- Create schema_migrations table for tracking applied migrations
CREATE TABLE IF NOT EXISTS schema_migrations (
    version INTEGER PRIMARY KEY,
    applied_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    description TEXT
);

-- Create kitch_category table (if not exists)
CREATE TABLE IF NOT EXISTS kitch_category (
    category_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    category_name VARCHAR(50) NOT NULL UNIQUE,
    description TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create kitch_customer table (if not exists)
CREATE TABLE IF NOT EXISTS kitch_customer (
    cust_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    cust_name VARCHAR(100) NOT NULL,
    cust_phone_number VARCHAR(12) UNIQUE NOT NULL CHECK (cust_phone_number ~ '^[0-9]{10}$'),
    cust_email VARCHAR(100),
    cust_address TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create kitch_item_catalg table (if not exists)
CREATE TABLE IF NOT EXISTS kitch_item_catalg (
    kic_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    kic_name VARCHAR(100) NOT NULL,
    kic_price NUMERIC(10,2) NOT NULL CHECK (kic_price >= 0),
    category_id INTEGER REFERENCES kitch_category(category_id),
    description TEXT,
    is_catering BOOLEAN DEFAULT FALSE,
    is_active BOOLEAN DEFAULT TRUE,
    image_url VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create kitch_status table (if not exists)
CREATE TABLE IF NOT EXISTS kitch_status (
    status_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    status_name VARCHAR(50) NOT NULL UNIQUE,
    description TEXT,
    display_order INTEGER DEFAULT 0
);

-- Create kitch_payment table (if not exists)
CREATE TABLE IF NOT EXISTS kitch_payment (
    payment_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    payment_method VARCHAR(20) NOT NULL CHECK (payment_method IN ('cash', 'card', 'other')),
    payment_status VARCHAR(20) DEFAULT 'pending' CHECK (payment_status IN ('pending', 'paid', 'partially_paid', 'refunded')),
    amount NUMERIC(10,2) NOT NULL CHECK (amount >= 0),
    payment_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Insert default statuses if not exists
INSERT INTO kitch_status (status_name, description, display_order)
VALUES
    ('Pending', 'Order received and pending confirmation', 1),
    ('Confirmed', 'Order confirmed and in queue', 2),
    ('Preparing', 'Food is being prepared', 3),
    ('Ready', 'Order is ready for pickup', 4),
    ('Completed', 'Order completed and delivered', 5),
    ('Cancelled', 'Order cancelled', 6)
ON CONFLICT (status_name) DO NOTHING;

-- Insert default categories if not exists
INSERT INTO kitch_category (category_name, description)
VALUES
    ('Appetizers', 'Starters and small plates'),
    ('Main Course', 'Main dishes and entrees'),
    ('Desserts', 'Sweet endings'),
    ('Beverages', 'Drinks and refreshments'),
    ('Catering', 'Catering and party trays')
ON CONFLICT (category_name) DO NOTHING;
