-- Migration 002: Create user authentication tables

CREATE TABLE kitch_user (
    user_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    cust_id INTEGER REFERENCES kitch_customer(cust_id) ON DELETE SET NULL,
    username VARCHAR(50) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(20) DEFAULT 'customer' CHECK (role IN ('customer', 'staff', 'admin')),
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes for performance
CREATE INDEX idx_kitch_user_username ON kitch_user(username);
CREATE INDEX idx_kitch_user_cust_id ON kitch_user(cust_id);
CREATE INDEX idx_kitch_user_role ON kitch_user(role);
CREATE INDEX idx_kitch_user_is_active ON kitch_user(is_active);
