-- Migration 003: Create order management tables

CREATE TABLE kitch_order (
    order_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    order_ref VARCHAR(50) UNIQUE NOT NULL,
    cust_id INTEGER REFERENCES kitch_customer(cust_id) ON DELETE SET NULL,
    order_phone VARCHAR(12) NOT NULL CHECK (order_phone ~ '^[0-9]{10}$'),
    placed_by_user_id INTEGER REFERENCES kitch_user(user_id) ON DELETE SET NULL,
    order_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    subtotal NUMERIC(10,2) NOT NULL CHECK (subtotal >= 0),
    discount_amount NUMERIC(10,2) DEFAULT 0 CHECK (discount_amount >= 0),
    discount_type VARCHAR(10) CHECK (discount_type IN ('percent', 'fixed', NULL)),
    tip_amount NUMERIC(10,2) DEFAULT 0 CHECK (tip_amount >= 0),
    tax_amount NUMERIC(10,2) DEFAULT 0 CHECK (tax_amount >= 0),
    total_amount NUMERIC(10,2) NOT NULL CHECK (total_amount >= 0),
    payment_status VARCHAR(20) DEFAULT 'pending' CHECK (payment_status IN ('pending', 'paid', 'partially_paid', 'refunded', 'cancelled')),
    current_status_id INTEGER REFERENCES kitch_status(status_id),
    notes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE kitch_order_item (
    order_item_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    order_id INTEGER NOT NULL REFERENCES kitch_order(order_id) ON DELETE CASCADE,
    kic_id INTEGER REFERENCES kitch_item_catalg(kic_id) ON DELETE SET NULL,
    name VARCHAR(100) NOT NULL,
    unit_price NUMERIC(10,2) NOT NULL CHECK (unit_price >= 0),
    quantity INTEGER DEFAULT 1 CHECK (quantity > 0),
    special_instructions TEXT,
    is_catering BOOLEAN DEFAULT FALSE,
    catering_size VARCHAR(10) CHECK (catering_size IN ('small', 'medium', 'large', NULL)),
    line_total NUMERIC(10,2) NOT NULL CHECK (line_total >= 0),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE kitch_order_status_history (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    order_id INTEGER NOT NULL REFERENCES kitch_order(order_id) ON DELETE CASCADE,
    status_id INTEGER NOT NULL REFERENCES kitch_status(status_id),
    changed_by_user_id INTEGER REFERENCES kitch_user(user_id) ON DELETE SET NULL,
    changed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    note TEXT
);

-- Create indexes for performance
CREATE INDEX idx_kitch_order_ref ON kitch_order(order_ref);
CREATE INDEX idx_kitch_order_cust_id ON kitch_order(cust_id);
CREATE INDEX idx_kitch_order_phone ON kitch_order(order_phone);
CREATE INDEX idx_kitch_order_date ON kitch_order(order_date);
CREATE INDEX idx_kitch_order_payment_status ON kitch_order(payment_status);
CREATE INDEX idx_kitch_order_current_status ON kitch_order(current_status_id);

CREATE INDEX idx_kitch_order_item_order_id ON kitch_order_item(order_id);
CREATE INDEX idx_kitch_order_item_kic_id ON kitch_order_item(kic_id);

CREATE INDEX idx_kitch_order_status_history_order_id ON kitch_order_status_history(order_id);
CREATE INDEX idx_kitch_order_status_history_changed_at ON kitch_order_status_history(changed_at);
