-- Migration 006: Add Order Edit Audit Trail and Supporting Features
-- Purpose: Enable order editing with full audit trail, payment overrides, and performance optimization

-- ============================================================================
-- 1. Order Edit Audit Trail Table
-- ============================================================================
-- Tracks all modifications to orders and order items for compliance and debugging
-- Uses JSONB for flexible storage of any field changes without schema modifications

CREATE TABLE IF NOT EXISTS kitch_order_edit_history (
    edit_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    order_id INTEGER NOT NULL REFERENCES kitch_order(order_id) ON DELETE CASCADE,
    entity_type VARCHAR(20) NOT NULL CHECK (entity_type IN ('order', 'order_item')),
    entity_id INTEGER NOT NULL,  -- order_id or order_item_id depending on entity_type
    action VARCHAR(20) NOT NULL CHECK (action IN ('update', 'delete', 'add_item')),
    changed_by_user_id INTEGER REFERENCES kitch_user(user_id) ON DELETE SET NULL,
    changed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    old_values JSONB,  -- Snapshot of values before change
    new_values JSONB,  -- Snapshot of values after change
    change_reason TEXT  -- Optional reason provided by staff
);

-- Indexes for audit trail queries
CREATE INDEX idx_order_edit_history_order_id ON kitch_order_edit_history(order_id);
CREATE INDEX idx_order_edit_history_changed_at ON kitch_order_edit_history(changed_at DESC);
CREATE INDEX idx_order_edit_history_entity ON kitch_order_edit_history(entity_type, entity_id);


-- ============================================================================
-- 2. Payment Override Tracking
-- ============================================================================
-- Allow staff to override payment amount and track the reason

ALTER TABLE kitch_payment
ADD COLUMN IF NOT EXISTS override_amount NUMERIC(10,2) CHECK (override_amount >= 0),
ADD COLUMN IF NOT EXISTS override_reason TEXT,
ADD COLUMN IF NOT EXISTS override_by_user_id INTEGER REFERENCES kitch_user(user_id) ON DELETE SET NULL;


-- ============================================================================
-- 3. Performance Indexes for Dashboard
-- ============================================================================
-- Composite index for daily dashboard queries (order_date + status filtering)
-- Partial index excludes cancelled orders to reduce index size

CREATE INDEX IF NOT EXISTS idx_kitch_order_date_status
ON kitch_order(order_date DESC, current_status_id)
WHERE payment_status != 'cancelled';

-- Index for pagination queries (order_date + order_id for tie-breaking)
CREATE INDEX IF NOT EXISTS idx_kitch_order_date_pagination
ON kitch_order(order_date DESC, order_id DESC);


-- ============================================================================
-- 4. Add "Delivered" Status
-- ============================================================================
-- Need explicit "Delivered" state to trigger auto-transition to "Complete" on payment
-- Inserting with display_order 4.5 to fit between Ready (4) and Completed (5)

INSERT INTO kitch_status (status_name, description, display_order)
VALUES ('Delivered', 'Order delivered to customer', 4.5)
ON CONFLICT (status_name) DO NOTHING;

-- Update existing status display orders to accommodate new status
UPDATE kitch_status SET display_order = 5 WHERE status_name = 'Completed';
UPDATE kitch_status SET display_order = 6 WHERE status_name = 'Cancelled';


-- ============================================================================
-- 5. Add updated_at Timestamp to Order Items (for optimistic locking)
-- ============================================================================
-- Enables concurrency control to prevent conflicting edits

ALTER TABLE kitch_order_item
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

-- Create trigger to auto-update updated_at on changes
CREATE OR REPLACE FUNCTION update_kitch_order_item_timestamp()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_update_kitch_order_item_timestamp
BEFORE UPDATE ON kitch_order_item
FOR EACH ROW
EXECUTE FUNCTION update_kitch_order_item_timestamp();


-- ============================================================================
-- 6. Migration Complete
-- ============================================================================

-- Verify tables exist
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'kitch_order_edit_history') THEN
        RAISE NOTICE 'Migration 006 completed successfully: Order edit audit trail system ready';
    ELSE
        RAISE EXCEPTION 'Migration 006 failed: kitch_order_edit_history table not created';
    END IF;
END $$;
