-- Migration 008: Create receipt management tables for operating cost tracking

-- Table for storing receipt metadata
CREATE TABLE kitch_receipt (
    receipt_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    shop_name VARCHAR(100),
    receipt_date TIMESTAMP,
    total_amount NUMERIC(10,2) NOT NULL CHECK (total_amount >= 0),
    image_path VARCHAR(255) NOT NULL,
    uploaded_by INTEGER REFERENCES kitch_user(user_id),
    raw_data JSONB, -- Stores the full extraction result for reference
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Table for storing individual items from a receipt
CREATE TABLE kitch_receipt_item (
    item_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    receipt_id INTEGER NOT NULL REFERENCES kitch_receipt(receipt_id) ON DELETE CASCADE,
    item_name VARCHAR(255) NOT NULL,
    quantity NUMERIC(10,3),
    unit_price NUMERIC(10,2),
    total_price NUMERIC(10,2) NOT NULL CHECK (total_price >= 0),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Indexes for performance
CREATE INDEX idx_kitch_receipt_date ON kitch_receipt(receipt_date);
CREATE INDEX idx_kitch_receipt_uploaded_by ON kitch_receipt(uploaded_by);
CREATE INDEX idx_kitch_receipt_item_receipt_id ON kitch_receipt_item(receipt_id);
CREATE INDEX idx_kitch_receipt_shop_name ON kitch_receipt(shop_name);
